---

- name: Web server installations
  hosts: webservers
  become_user: root
  become: true
  vars_files:
    - env_vars/base.yml
  vars:
    ansible_become_pass: "{{ server_user_password }}"
  roles:
    - firewall
    - createuser
