---

- name: Web server installations
  hosts: webservers
  gather_facts: no
  become_user: root
  become: true
  vars_files:
    - env_vars/base.yml
  roles:
    - role: firewall
      tags:
        - firewall
    - role: createuser
      tags:
        - createuser
    - role: base-installations
      tags:
        - base-installations