---

- name: Projects Deployment
  hosts: webservers
  gather_facts: no
  become: true
  become_user: "{{ server_user }}"
  vars_files:
    - env_vars/base.yml
    - env_vars/projects.yml
  vars:
    ansible_become_pass: "{{ server_user_password }}"
  roles:
    - role: deploy-projects
      tags:
        - deploy-projects
    - role: remove-projects
      tags:
        - remove-projects