---
    
- name: Create Server user
  user:
    name: "{{ server_user }}"
    password: "{{ server_user_password | string | password_hash('sha512') }}"
    shell: /bin/bash
    update_password: on_create
    
- name: Add authorized key
  authorized_key:
    user: "{{ server_user }}"
    key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
    exclusive: yes
    
- name: Allow sudo for server_user
  become: true
  copy:
    content: "{{ server_user }} ALL=(ALL) ALL"
    dest: /etc/sudoers.d/{{ server_user }}
    mode: 0440
    
- name: Disallow root SSH access
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PermitRootLogin"
              line="PermitRootLogin no"
              state=present           
  notify: restart sshd
  
- name: Disable password access
  lineinfile: dest=/etc/ssh/sshd_config
              line="PasswordAuthentication no"
              state=present
  notify: restart sshd
  
- name: Change permissions on home directory
  file:
    path: /home/{{ server_user }}
    mode: '0755'
    
- include_tasks: copy_ssh.yml


