- name: Ensure git is installed
  become_user: "{{ server_user }}"
  become: yes
  apt:
    state: present
    name:
      - git


# - name: Git config user email
#   become_user: "{{ server_user }}"
#   become: yes
#   git_config:
#      name: user.email
#      value: "{{ git_user_email }}"
#      scope: global
#
# - name: Git config user name
#   become_user: "{{ server_user }}"
#   become: yes
#   git_config:
#      name: user.name
#      value: "{{ git_user_name }}"
#      scope: global