---

- name: Install Uncomplicated Firewall
  apt:
    update_cache: true
    cache_valid_time: 3600
    state: present
    pkg: ufw
    
- name: Block any communications to private networks
  ufw:
      rule: deny
      direction: out
      to_ip: "{{ item }}"
  with_items:
    - "{{ ufw_private_networks }}"   
    
- name: Allow ssh and http(s) connections
  ufw: rule=allow port={{ item }}
  with_items:
    - "{{ ufw_allowed_ports }}"

- name: Enable ufw/firewall
  ufw: state=enabled policy=deny 
