---
- name: Make sure project directory exists
  ansible.builtin.file:
    path: "{{ sites_path }}/{{ item.domain }}/{{ item.name }}"
    state: directory
    
- name: Copy env_file
  ansible.builtin.copy:
    src: "{{ item.env_file}}"
    dest: "{{ sites_path }}/{{ item.domain }}/{{ item.name }}"

- name: Create docker compose for django
  template:
    src: docker/django.j2
    dest: "{{ sites_path }}/{{ item.domain }}/{{ item.name }}/docker-compose-django.yml"
  vars:
    pull_from: "{{ item.pull_from }}"
    wsgi_path: "{{ item.wsgi_path }}"
    domain: "{{ item.domain }}"
    name: "{{ item.name }}"
    media_volume: "{{ item.media_volume | d(false)}}"
    postgres: "{{ item.postgres | d(false)}}"
    env_file: "{{ item.env_file | basename}}"

- name: Make sure docker compose backend service has been stopped.
  community.docker.docker_compose_v2:
    project_src: "{{ sites_path }}/{{ item.domain }}/{{ item.name }}"
    state: stopped
    files: 
      - docker-compose-django.yml

- name: Pull image and start docker compose backend 
  block:
    - name: Pull image and start docker compose backend 
      community.docker.docker_compose_v2:
        project_src: "{{ sites_path }}/{{ item.domain }}/{{ item.name }}"
        state: present
        files: 
          - docker-compose-django.yml
        pull: always
        remove_orphans: true
        services:
          - backend-{{item.name}}
      register: output
      notify:
        - restart nginx
      when:
        - not item.postgres | d(false)
    
    - name: Show output-backend
      ansible.builtin.debug:
        msg: "{{ output }}"
        
- name: Pull image and start docker compose backend and postgres db
  block:
    - name: Pull image and start docker compose backend and postgres db
      community.docker.docker_compose_v2:
        project_src: "{{ sites_path }}/{{ item.domain }}/{{ item.name }}"
        state: present
        files: 
          - docker-compose-django.yml
        pull: always
        remove_orphans: true
        services:
          - db-{{item.name}}
          - backend-{{item.name}}
      register: output
      notify:
        - restart nginx
      when:
        - item.postgres | d(false)
    - name: Show output
      ansible.builtin.debug:
        msg: "{{ output }}"