---
- name: Checkout git repository
  include_tasks: git.yml
  loop : "{{ projects }}"
  when: 
    - item.repository | d(false)
    - item.state == 'present'
  tags:
    - git

- name: Copy html folder
  include_tasks: copy-html-folder.yml
  loop : "{{ projects }}"
  when: 
    - item.state == 'present'
    - item.type == "html"
  tags:
    - copy-html

- name: Create and run djanago docker compose 
  include_tasks: django-docker-compose.yml
  loop : "{{ projects }}"
  when: 
    - item.state == 'present'
    - item.type == "django"
  tags:
    - django
    
- name: Create sites available files
  include_tasks: nginx-sites-available-file.yml
  loop : "{{ projects }}"
  when: 
    - item.state == 'present'
  tags:
    - nginx-sites
