- name: Stop certbot-renewal container if ssl is false
  community.docker.docker_container:
    name: "certbot-renewal-{{ item.domain }}"
    state: absent
  when:
    - not item.ssl | default(false)
        
- name: Make sure certbot folder exists in project
  ansible.builtin.file:
    path: "{{ sites_path }}/{{ item.domain }}/certbot"
    state: directory

- name: Create a docker-compose-certbot.yml file in project/certbot directory
  template:
    src: docker/certbot.j2
    dest: "{{ sites_path }}/{{ item.domain }}/certbot/docker-compose-certbot.yml"
  vars:
    domain: "{{ item.domain }}"
    name: "{{ item.name }}"
    
- name: Check for certificate and create it if necessary
  block:
    - name: Check if certificate exists
      become: yes
      become_user: root
      stat:
        path: "{{ certbot_path}}/letsencrypt/live/{{ item.domain }}/fullchain.pem"
      register: certificate
      
    - name: Check if domain is registered as "staging"
      become: yes
      become_user: root
      stat:
        path: "{{ certbot_path }}/staging/{{ item.domain }}"
      register: staging
    
    - name: Create certificate if necessary
      include_tasks: create-certificate.yml
      when: not certificate.stat.exists or 
            (not item.staging | d(false) and staging.stat.exists) or
            (item.staging | d(false) and not staging.stat.exists)
      
  when:
    - item.ssl | default(false)
    
- name: Start certbot-renewal service
  community.docker.docker_compose_v2:
    project_src: "{{ sites_path }}/{{ item.domain }}/certbot"
    services: 
      - "certbot-renewal"
    remove_orphans: true
    files:
      - docker-compose-certbot.yml
    project_name: "{{ item.name }}-certbot-renew"
    state: present
  when:
    - item.ssl | default(false)

- name: Creating nginx sites-enables file for domain
  block:
  - name: Create html 80 nginx sites-enabled for domain
    template:
      src: nginx/html-80.j2
      dest: "{{ sites_path }}/etc/nginx/sites-enabled/{{ item.domain}}"
    vars:
      domain: "{{ item.domain }}"
    when:
      - not item.ssl | default(false)
      - item.type == "html"

  - name: Create html 443 nginx sites-enabled for domain
    template:
      src: nginx/html-443.j2
      dest: "{{ sites_path }}/etc/nginx/sites-enabled/{{ item.domain}}"
    vars:
      domain: "{{ item.domain }}"
    when:
      - item.ssl | default(false)
      - item.type == "html"

  - name: Create django 80 nginx sites-enabled for domain
    template:
      src: nginx/django-80.j2
      dest: "{{ sites_path }}/etc/nginx/sites-enabled/{{ item.domain}}"
    vars:
      domain: "{{ item.domain }}"
      name: "{{ item.name }}"
      proxy_name: "{{ item.name | replace('-','_')}}"
    when:
      - not item.ssl | default(false)
      - item.type == "django"
  
  - name: Create django 443 nginx sites-enabled for domain
    template:
      src: nginx/django-443.j2
      dest: "{{ sites_path }}/etc/nginx/sites-enabled/{{ item.domain}}"
    vars:
      domain: "{{ item.domain }}"
      name: "{{ item.name }}"
      proxy_name: "{{ item.name | replace('-','_')}}"
    when:
      - item.ssl | default(false)
      - item.type == "django"
        
  notify:
    restart nginx
