---
- name: Checkout project repository
  become: yes
  become_user: "{{ server_user }}"
  git:
     repo: "{{item.repository}}"
     version: "{{ item.git_version | default('master')}}"
     dest: "{{ sites_path }}/{{ item.domain }}/{{ item.name }}"
     force: yes
     accept_hostkey: yes
  with_items: "{{ projects }}"
  when: 
    - item.repository
    - item.state == 'present'

- name: Remove "{{ sites_path }}/DOMAIN_NAME"
  become: yes
  file:
    path: "{{ sites_path }}/{{ item.domain }}"
    state: absent
  with_items: "{{ projects }}"
  when: item.state != 'present'

