server_user: <YOUR_SERVER_USERNAME>
server_user_password: !vault |
                      $ANSIBLE_VAULT;1.1;AES256
                      39343731356138303334626561366262663664373266373932383937643035356563346238643665
                      ...
ssh_key_file_name: <YOUR_SSH_KEY_FILE_NAME>
local_public_ssh_key_path: ~/.ssh/id_ed25519.pub
sites_path: "/home/{{ server_user }}/sites"

# git_user_email: <YOUR_GIT_USER_EMAIL>
# git_user_name: <YOUR_GIT_USER_NAME>

certbot_email: <YOUR_CERTBOT_EMAIL>
certbot_path: /home/{{ server_user }}/certbot