- name: Remove project
  become: yes
  become_user: root
  block:
  - name: Remove config file from enabled sites
    file:
      path: "{{ sites_path }}/etc/nginx/sites-enabled/{{ item.domain }}"
      state: absent
  
  - name: Django docker compose down
    community.docker.docker_compose_v2:
      project_src: "{{ sites_path }}/{{ item.domain }}/{{ item.name }}"
      state: absent
      files: 
        - docker-compose-django.yml
      remove_orphans: true
    when:
      - item.type == 'django'

  - name: Stop certbot renewal container if needed
    community.docker.docker_container:
      name: "certbot-renewal-{{ item.domain }}"
      state: absent
      
  - name: Remove folder from /var/www/
    file:
      path: "{{ sites_path }}/var/www/{{ item.domain }}"
      state: absent
    
  - name: Remove "{{ sites_path }}/DOMAIN_NAME"
    file:
      path: "{{ sites_path }}/{{ item.domain }}"
      state: absent


  notify: restart nginx

