- name: Create docker compose html-80
  ansible.builtin.template:
    src: html-80.j2
    dest: "{{ sites_path }}/{{ item.domain }}/docker-compose.yml"
  vars:
    domain: "{{ item.domain }}"
    name: "{{ item.name }}"
  with_items: "{{ projects }}"
  when:
    - item.state == 'present'
    - not item.ssl | default(false)
    - item.type == "html"
    
- name: Start or stop docker compose
  community.docker.docker_compose_v2:
    project_src: "{{ sites_path }}/{{ item.domain }}"
    pull: 'always'
    remove_orphans: true
    state: "{{ item.state }}"
  with_items: "{{ projects }}"