- name: Make sure nginx/sites-enabled/ exists
  become: yes
  become_user: "{{ server_user }}"
  ansible.builtin.file:
    path: "{{ sites_path }}/etc/nginx/sites-enabled/"
    state: directory

- name: Create the Nginx configuration file
  become: yes
  ansible.builtin.copy:
    src: nginx.conf
    dest: "{{ sites_path }}/etc/nginx/"
    
    
- name: Create docker compose file nginx
  become: yes
  become_user: "{{ server_user }}"
  template:
    src: docker-compose-nginx.j2
    dest: "{{ sites_path }}/docker-compose-nginx.yml"


- name: Start docker compose file nginx
  community.docker.docker_compose_v2:
    project_src: "{{ sites_path }}"
    files:
      - docker-compose-nginx.yml
    remove_orphans: true
    state: present
